models/Overhead.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "overhead".
 *
 * @property int $id
 * @property string $city_out Город отправки
 * @property string $city_in Город доставки
 * @property string $recipient Получатель
 * @property int $status_id Статус
 *
 * @property Status $status
 */
class Overhead extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'overhead';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['city_out', 'city_in', 'recipient', 'status_id'], 'required'],
            [['status_id'], 'integer'],
            [['city_out', 'city_in', 'recipient'], 'string', 'max' => 255],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['status_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','ID'),
            'city_out' => Yii::t('app','Откуда'),
            'city_in' => Yii::t('app','Куда'),
            'recipient' => Yii::t('app','Получатель'),
            'status_id' => Yii::t('app','Статус'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }
}

controllers/OverheadController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Overhead;
use app\models\OverheadSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * OverheadController implements the CRUD actions for Overhead model.
 */
class OverheadController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Overhead models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OverheadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Overhead model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Overhead model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Overhead();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return [ 'status' => 'success'];
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Overhead model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return [ 'status' => 'success'];
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Overhead model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Overhead model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Overhead the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Overhead::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionValidate()
    {
        $model = new Overhead();
        $request = \Yii::$app->getRequest();
        if ($request->isAjax && $model->load($request->post())) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
}

views/overhead/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OverheadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="overhead-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'sity_out') ?>

    <?= $form->field($model, 'sity_in') ?>

    <?= $form->field($model, 'recipient') ?>

    <?= $form->field($model, 'status_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/overhead/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Status;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model app\models\Overhead */

$this->title = 'Создать накладную';

?>
<div class="overhead-create">

    <h1><?= Html::encode($this->title) ?></h1>
        <?php $form = ActiveForm::begin([
                'id' => 'create_form',
                'enableAjaxValidation' => true,
                'validationUrl' => Url::toRoute(['overhead/validate'])
        ]); ?>

        <?= $form->field($model, 'city_out')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'city_in')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'recipient')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'status_id')->dropDownList(Status::getStatusList()) ?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/overhead/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OverheadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Накладные';
?>
<div class="overhead-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::button('Создать', ['class' => 'btn btn-success create_overhead']) ?>
    </p>
    <?php Pjax::begin(['id' => 'table-grid-pjax']) ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'city_out',
                'city_in',
                'recipient',
                [
                  'attribute' => 'status_id',
                  'value' => function($data) {
                    return $data->status->title;
                  }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{update} {delete}',
                    'buttons' => [
                        'update' => function ($url, $model) {
                            return Html::a("<span class='glyphicon glyphicon-pencil'></span>", '', [
                                'title' => Yii::t('app', 'view'),
                                'onclick' => 'updateOverhead(' . $model->id . ')'
                            ]);
                        },
                    ],
                ],
            ],
        ]); ?>
    <?php Pjax::end() ?>
</div>
<?php  Modal::begin(['id' => 'overhead_modal']) ?>
<?php Modal::end() ?>

views/overhead/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Status;

/* @var $this yii\web\View */
/* @var $model app\models\Overhead */

$this->title = 'Обновить накладную №' . $model->id;

?>
<div class="overhead-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin([
        'id' => 'update_form',
        'enableAjaxValidation' => true,
        'validationUrl' => Url::toRoute(['overhead/validate'])
    ]); ?>

    <?= $form->field($model, 'city_out')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'city_in')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'recipient')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status_id')->dropDownList(Status::getStatusList()) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/overhead/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Overhead */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Overheads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="overhead-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'sity_out',
            'sity_in',
            'recipient',
            'status_id',
        ],
    ]) ?>

</div>